baseURL = 'https://ItsMonish.github.io/'
languageCode = 'en-us'
enableRobotsTXT = true
title = "Monish Kumar's Blog"

theme = "hugo-theme-stack"

[caches]
[caches.images]
dir = ':cacheDir/images'

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
