module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - blog
    featuredImageField:
    rssFullContent: true

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 IST

    sidebar:
        compact: false
        emoji:
        subtitle: 
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        homepage: 
            - type: "search"
            - type: "categories"
              limit: 10
            - type: "tag-cloud"
        page: 
            - type: "toc"

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
    - identifier: "about"
      name: "About"
      weight: -90
      url: "/about"
      params:
            icon: user
    - identifier: "home"
      name: "Home"
      weight: -100
      url: "/"
      params:
            icon: home
    social:
        - identifier: "github"
          name: "Github"
          url: "https://github.com/ItsMonish"
          weight: -110
          params:
              icon: brand-github
        - identifier: "linkedin"
          name: "LinkedIn"
          url: "https://www.linkedin.com/in/monish-kumar-a-b17119281/"
          weight: -110
          params:
              icon: brand-linkedin
        - identifier: "mail"
          name: "Mail"
          url: "mailto:monishkumar03@protonmail.com"
          weight: -110
          params:
              icon: mail
